server:
  port: 9011
spring:
  application:
    name: 注册中心-01
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9012/eureka/ #与 Eureka Server 交互的地址
  instance:
    hostname: 127.0.0.1