server:
  port: 9010
spring:
  datasource:
    type: com.zaxxer.hikari.util.DriverDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://www.lxjn.club:3306/lxjn_club?useUnicode=true&characterEncoding=utf8
    data-username: lxjn_club
    data-password: 123456
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化提供的连接数
      max-total: 5 #最大的连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间

